/*
# ===============================================================================
#                      PRIMARK
#
# ===============================================================================
# ===============================================================================
# File Name           : OLR1001.100.TRANS.sql
# Pattern             : 
# Purpose             : Insertion in TRANS table
# Author              : TERADATA
# File Type           : SQL
# Creation Date       : 2025-07-20
# -------------------------------------------------------------------------------
# Change History :
# Ver  | Date        |  Modified By           |  Change Description
# -------------------------------------------------------------------------------
# Automatically generated by 10cents_table_generator
# 1.0  | 2025-07-20 | TERADATA               |  INITIAL CODE
# Build Time 21:27:25
# 1.0  | 2025-07-20 | TERADATA               |  INITIAL CODE
*/

BEGIN TRANSACTION
;
.IF ERRORCODE <> 0 THEN .QUIT 101

/* Lock target table */
LOCKING DW${INSTANCE}V_ACC_TMP.DM_FND_STORE_HIER_HIST_DIM FOR WRITE
;
.IF ERRORCODE <> 0 THEN .QUIT 101

/* Update the target table by closing of the previous records */
UPDATE TRG FROM  DW${INSTANCE}V_ACC_TMP.DM_FND_STORE_HIER_HIST_DIM AS TRG
                ,DW${INSTANCE}T_TMP_ACC_FND.FND1013_VALID AS SRC
SET eff_to_dt = date '${EFF_FROM}' 
  , update_job_id = '${JOB}'
  , update_run_id = '${RUN_ID}'
WHERE TRG.eff_to_dt = '9999-12-31'
AND eff_from_dt < date '${EFF_FROM}'
AND TRG.calendar_dt = TRANS.SRC.calendar_dt 
    
;
.IF ERRORCODE <> 0 THEN .QUIT 101

/* INSERT INTO target table */
INSERT INTO DW${INSTANCE}V_ACC_TMP.DM_FND_STORE_HIER_HIST_DIM
(
    calendar_dt, 
    year_start_dt, 
    year_end_dt, 
    period_start_dt, 
    period_end_dt, 
    week_start_dt, 
    week_end_dt, 
    day_of_year_num, 
    day_of_period_num, 
    day_of_week_num, 
    week_of_year_num, 
    week_of_period_num, 
    period_of_year_num, 
    year_week, 
    year_period, 
    year_num, 
    ly_calendar_dt, 
    ly_year_start_dt, 
    ly_year_end_dt, 
    ly_period_start_dt, 
    ly_period_end_dt, 
    ly_week_start_dt, 
    ly_week_end_dt, 
    ly_day_of_year_num, 
    ly_day_of_period_num, 
    ly_day_of_week_num, 
    ly_week_of_year_num, 
    ly_week_of_period_num, 
    ly_period_of_year_num, 
    ly_year_week, 
    ly_year_period, 
    ly_year_num, 
    lly_calendar_dt, 
    lly_year_start_dt, 
    lly_year_end_dt, 
    lly_period_start_dt, 
    lly_period_end_dt, 
    lly_week_start_dt, 
    lly_week_end_dt, 
    lly_day_of_year_num, 
    lly_day_of_period_num, 
    lly_day_of_week_num, 
    lly_week_of_year_num, 
    lly_week_of_period_num, 
    lly_period_of_year_num, 
    lly_year_week, 
    lly_year_period, 
    lly_year_num, 
    llly_calendar_dt, 
    llly_year_start_dt, 
    llly_year_end_dt, 
    llly_period_start_dt, 
    llly_period_end_dt, 
    llly_week_start_dt, 
    llly_week_end_dt, 
    llly_day_of_year_num, 
    llly_day_of_period_num, 
    llly_day_of_week_num, 
    llly_week_of_year_num, 
    llly_week_of_period_num, 
    llly_period_of_year_num, 
    llly_year_week, 
    llly_year_period, 
    llly_year_num, 
    ny_calendar_dt, 
    ny_year_start_dt, 
    ny_year_end_dt, 
    ny_period_start_dt, 
    ny_period_end_dt, 
    ny_week_start_dt, 
    ny_week_end_dt, 
    ny_day_of_year_num, 
    ny_day_of_period_num, 
    ny_day_of_week_num, 
    ny_week_of_year_num, 
    ny_week_of_period_num, 
    ny_period_of_year_num, 
    ny_year_week, 
    ny_year_period, 
    ny_year_num, 
    /* Control Columns */
    eff_from_dt,
    eff_to_dt,
    del_ind,
    run_id,
    update_run_id,
    job_id,
    update_job_id
)

SELECT
    SRC.calendar_dt AS calendar_dt
    SRC.year_start_dt AS year_start_dt
    SRC.year_end_dt AS year_end_dt
    SRC.period_start_dt AS period_start_dt
    SRC.period_end_dt AS period_end_dt
    SRC.week_start_dt AS week_start_dt
    SRC.week_end_dt AS week_end_dt
    SRC.day_of_year_num AS day_of_year_num
    SRC.day_of_period_num AS day_of_period_num
    SRC.day_of_week_num AS day_of_week_num
    SRC.week_of_year_num AS week_of_year_num
    SRC.week_of_period_num AS week_of_period_num
    SRC.period_of_year_num AS period_of_year_num
    SRC.year_week AS year_week
    SRC.year_period AS year_period
    SRC.year_num AS year_num
    SRC.ly_calendar_dt AS ly_calendar_dt
    SRC.ly_year_start_dt AS ly_year_start_dt
    SRC.ly_year_end_dt AS ly_year_end_dt
    SRC.ly_period_start_dt AS ly_period_start_dt
    SRC.ly_period_end_dt AS ly_period_end_dt
    SRC.ly_week_start_dt AS ly_week_start_dt
    SRC.ly_week_end_dt AS ly_week_end_dt
    SRC.ly_day_of_year_num AS ly_day_of_year_num
    SRC.ly_day_of_period_num AS ly_day_of_period_num
    SRC.ly_day_of_week_num AS ly_day_of_week_num
    SRC.ly_week_of_year_num AS ly_week_of_year_num
    SRC.ly_week_of_period_num AS ly_week_of_period_num
    SRC.ly_period_of_year_num AS ly_period_of_year_num
    SRC.ly_year_week AS ly_year_week
    SRC.ly_year_period AS ly_year_period
    SRC.ly_year_num AS ly_year_num
    SRC.lly_calendar_dt AS lly_calendar_dt
    SRC.lly_year_start_dt AS lly_year_start_dt
    SRC.lly_year_end_dt AS lly_year_end_dt
    SRC.lly_period_start_dt AS lly_period_start_dt
    SRC.lly_period_end_dt AS lly_period_end_dt
    SRC.lly_week_start_dt AS lly_week_start_dt
    SRC.lly_week_end_dt AS lly_week_end_dt
    SRC.lly_day_of_year_num AS lly_day_of_year_num
    SRC.lly_day_of_period_num AS lly_day_of_period_num
    SRC.lly_day_of_week_num AS lly_day_of_week_num
    SRC.lly_week_of_year_num AS lly_week_of_year_num
    SRC.lly_week_of_period_num AS lly_week_of_period_num
    SRC.lly_period_of_year_num AS lly_period_of_year_num
    SRC.lly_year_week AS lly_year_week
    SRC.lly_year_period AS lly_year_period
    SRC.lly_year_num AS lly_year_num
    SRC.llly_calendar_dt AS llly_calendar_dt
    SRC.llly_year_start_dt AS llly_year_start_dt
    SRC.llly_year_end_dt AS llly_year_end_dt
    SRC.llly_period_start_dt AS llly_period_start_dt
    SRC.llly_period_end_dt AS llly_period_end_dt
    SRC.llly_week_start_dt AS llly_week_start_dt
    SRC.llly_week_end_dt AS llly_week_end_dt
    SRC.llly_day_of_year_num AS llly_day_of_year_num
    SRC.llly_day_of_period_num AS llly_day_of_period_num
    SRC.llly_day_of_week_num AS llly_day_of_week_num
    SRC.llly_week_of_year_num AS llly_week_of_year_num
    SRC.llly_week_of_period_num AS llly_week_of_period_num
    SRC.llly_period_of_year_num AS llly_period_of_year_num
    SRC.llly_year_week AS llly_year_week
    SRC.llly_year_period AS llly_year_period
    SRC.llly_year_num AS llly_year_num
    SRC.ny_calendar_dt AS ny_calendar_dt
    SRC.ny_year_start_dt AS ny_year_start_dt
    SRC.ny_year_end_dt AS ny_year_end_dt
    SRC.ny_period_start_dt AS ny_period_start_dt
    SRC.ny_period_end_dt AS ny_period_end_dt
    SRC.ny_week_start_dt AS ny_week_start_dt
    SRC.ny_week_end_dt AS ny_week_end_dt
    SRC.ny_day_of_year_num AS ny_day_of_year_num
    SRC.ny_day_of_period_num AS ny_day_of_period_num
    SRC.ny_day_of_week_num AS ny_day_of_week_num
    SRC.ny_week_of_year_num AS ny_week_of_year_num
    SRC.ny_week_of_period_num AS ny_week_of_period_num
    SRC.ny_period_of_year_num AS ny_period_of_year_num
    SRC.ny_year_week AS ny_year_week
    SRC.ny_year_period AS ny_year_period
    SRC.ny_year_num AS ny_year_num
    SRC.eff_from_dt,
    SRC.eff_to_dt,
    SRC.del_ind,
    SRC.run_id,
    SRC.update_run_id,
    SRC.job_id,
    SRC.update_job_id
FROM DW${INSTANCE}T_TMP_ACC_FND.FND1013_VALID AS SRC
;
.IF ERRORCODE <> 0 THEN .QUIT 101

/* End of INSERT statement */


END TRANSACTION
.IF ERRORCODE <> 0 THEN .QUIT 101