/*
# ===============================================================================
#                      PRIMARK
#
# ===============================================================================
# ===============================================================================
# File Name           : FND1023.300.TARGET.sql
# Pattern             : 
# Purpose             : Trans Bespoke step
# Author              : TERADATA
# File Type           : SQL
# Creation Date       : 2025-08-06
# -------------------------------------------------------------------------------
# Change History :
# Ver  | Date        |  Modified By           |  Change Description
# -------------------------------------------------------------------------------
# Automatically generated by 10cents_table_generator
# 1.0  | 2025-08-06 | TERADATA               |  INITIAL CODE
# Build Time 08:39:35
# 1.0  | 2025-08-06 | TERADATA               |  INITIAL CODE
*/



.IF ERRORCODE <> 0 THEN .QUIT 101



/* End of step */