/*
# ===============================================================================
#                      PRIMARK
#
# ===============================================================================
# ===============================================================================
# File Name           : OLR1001.100.TRANS.sql
# Pattern             : 
# Purpose             : Insertion in TRANS table
# Author              : TERADATA
# File Type           : SQL
# Creation Date       : 2025-07-23
# -------------------------------------------------------------------------------
# Change History :
# Ver  | Date        |  Modified By           |  Change Description
# -------------------------------------------------------------------------------
# Automatically generated by 10cents_table_generator
# 1.0  | 2025-07-23 | TERADATA               |  INITIAL CODE
# Build Time 15:46:13
# 1.0  | 2025-07-23 | TERADATA               |  INITIAL CODE
*/

BEGIN TRANSACTION
;
.IF ERRORCODE <> 0 THEN .QUIT 101

/* Lock target table */
LOCKING DW${INSTANCE}V_ACC_FND.DM_FND_STORE_HIER_DIM FOR WRITE
;
.IF ERRORCODE <> 0 THEN .QUIT 101

/* Update the target table by closing of the previous records */
UPDATE TRG FROM  DW${INSTANCE}V_ACC_FND.DM_FND_STORE_HIER_DIM AS TRG
                ,DW${INSTANCE}T_TMP_ACC_FND.FND1041_VALID AS SRC
SET eff_to_dt = SRC.eff_from_dt
  , update_job_id = SRC.job_id
  , update_run_id = SRC.run_id
WHERE TRG.eff_to_dt = '9999-12-31'
AND TRG.item_sbclas_wid = SRC.item_sbclas_wid 
    
;
.IF ERRORCODE <> 0 THEN .QUIT 101

/* INSERT INTO target table */
INSERT INTO DW${INSTANCE}V_ACC_FND.DM_FND_STORE_HIER_DIM
(
    item_sbclas_wid, 
    pmk_co_cd, 
    pmk_co_vers_num, 
    dvisn_cd, 
    dvisn_vers_num, 
    dept_cd, 
    dept_vers_num, 
    item_clas_cd, 
    item_clas_vers_num, 
    pmk_item_sbclas_grp_cd, 
    pmk_item_sbclas_grp_vers_num, 
    item_sbclas_cd, 
    item_sbclas_vers_num, 
    /* Control Columns */
    eff_from_dt,
    eff_to_dt,
    del_ind,
    run_id,
    update_run_id,
    job_id,
    update_job_id
)

SELECT
    SRC.item_sbclas_wid AS item_sbclas_wid, 
    SRC.pmk_co_cd AS pmk_co_cd, 
    SRC.pmk_co_vers_num AS pmk_co_vers_num, 
    SRC.dvisn_cd AS dvisn_cd, 
    SRC.dvisn_vers_num AS dvisn_vers_num, 
    SRC.dept_cd AS dept_cd, 
    SRC.dept_vers_num AS dept_vers_num, 
    SRC.item_clas_cd AS item_clas_cd, 
    SRC.item_clas_vers_num AS item_clas_vers_num, 
    SRC.pmk_item_sbclas_grp_cd AS pmk_item_sbclas_grp_cd, 
    SRC.pmk_item_sbclas_grp_vers_num AS pmk_item_sbclas_grp_vers_num, 
    SRC.item_sbclas_cd AS item_sbclas_cd, 
    SRC.item_sbclas_vers_num AS item_sbclas_vers_num, 
    SRC.eff_from_dt,
    SRC.eff_to_dt,
    SRC.del_ind,
    SRC.run_id,
    SRC.update_run_id,
    SRC.job_id,
    SRC.update_job_id
FROM DW${INSTANCE}T_TMP_ACC_FND.FND1041_VALID AS SRC
;
.IF ERRORCODE <> 0 THEN .QUIT 101

/* End of INSERT statement */


END TRANSACTION
.IF ERRORCODE <> 0 THEN .QUIT 101