/*
# ===============================================================================
#                      PRIMARK
#
# ===============================================================================
# ===============================================================================
# File Name           : OLR1001.100.TRANS.sql
# Pattern             : 
# Purpose             : Insertion in TRANS table
# Author              : TERADATA
# File Type           : SQL
# Creation Date       : 2025-07-24
# -------------------------------------------------------------------------------
# Change History :
# Ver  | Date        |  Modified By           |  Change Description
# -------------------------------------------------------------------------------
# Automatically generated by 10cents_table_generator
# 1.0  | 2025-07-24 | TERADATA               |  INITIAL CODE
# Build Time 08:26:58
# 1.0  | 2025-07-24 | TERADATA               |  INITIAL CODE
*/


DELETE FROM DW${INSTANCE}T_TMP_ACC_FND.FND1040_VALID
;

.IF ERRORCODE <> 0 THEN .QUIT 101

/*----------------------------------------------------------------------------

# Insert into target table
# This step inserts data into the target table from the source table.
# It uses a left outer join to detect changes and only inserts records that are new or have changed.
# The control columns are set to indicate the effective date range and deletion status.
# The run_id and job_id are also set for tracking purposes.

-------------------------------------------------------------------------------*/

INSERT INTO DW${INSTANCE}T_TMP_ACC_FND.FND1040_VALID
(
    styl_wid, 
    item_sbclas_wid, 
    styl_sbclass_vers_num, 
    /* Control Columnts */
    eff_from_dt,
    eff_to_dt,
    del_ind,
    run_id,
    update_run_id,
    job_id,
    update_job_id
)

SELECT
    TRANS.styl_wid, 
    TRANS.item_sbclas_wid, 
    TRANS.styl_sbclass_vers_num, 
    /* Control Columnts */
    date '${EFF_FROM_DATE}' AS eff_from_dt,
    DATE '3500-12-31' AS eff_to_dt,
    0 AS del_ind,
    ${RUNID} AS run_id,
    NULL AS update_run_id,
    '${JOB}' AS job_id,
    NULL AS update_job_id
FROM DW${INSTANCE}T_TMP_ACC_FND.FND1040_TRANS AS TRANS
LEFT OUTER JOIN DW${INSTANCE}T_ACC_FND.FND_RECLASFCN_STYL_SBCLASS_XREF AS TRG
ON  TRG.eff_to_dt = DATE '3500-12-31' /* Current effective record */
AND TRG.del_ind = 0 /* Not deleted */
AND TRG.styl_wid = TRANS.styl_wid 
    
WHERE (  /* Change detection */ 
    TRG.del_ind IS NULL /* No existing or a deleted */
OR TRG.item_sbclas_wid <> TRANS.item_sbclas_wid 
OR (TRG.item_sbclas_wid IS NULL AND TRANS.item_sbclas_wid IS NOT NULL)
OR (TRG.item_sbclas_wid IS NOT NULL AND TRANS.item_sbclas_wid IS NULL)
    
OR TRG.styl_sbclass_vers_num <> TRANS.styl_sbclass_vers_num 
OR (TRG.styl_sbclass_vers_num IS NULL AND TRANS.styl_sbclass_vers_num IS NOT NULL)
OR (TRG.styl_sbclass_vers_num IS NOT NULL AND TRANS.styl_sbclass_vers_num IS NULL)
    
) /* end of change detection */

;

.IF ERRORCODE <> 0 THEN .QUIT 101

/*------------------------------------------------------------------------------------------

# Insert deleted records into the valid table 
# these are records which are not present in source / transformation table 

-------------------------------------------------------------------------------------------*/

INSERT INTO DW${INSTANCE}T_TMP_ACC_FND.FND1040_VALID
(
    styl_wid, 
    item_sbclas_wid, 
    styl_sbclass_vers_num, 
    /* Control Columnts */
    eff_from_dt,
    eff_to_dt,
    del_ind,
    run_id,
    update_run_id,
    job_id,
    update_job_id
)

SELECT
    TRG.styl_wid, 
    TRG.item_sbclas_wid, 
    TRG.styl_sbclass_vers_num, 
    /* Control Columnts */
    date '${EFF_FROM_DATE}' AS eff_from_dt,
    DATE '3500-12-31' AS eff_to_dt,
    1 AS del_ind, /* Mark as deleted */
    ${RUNID} AS run_id,
    NULL AS update_run_id,
    '${JOB}' AS job_id,
    NULL AS update_job_id
FROM DW${INSTANCE}T_ACC_FND.FND_RECLASFCN_STYL_SBCLASS_XREF AS TRG
LEFT OUTER JOIN DW${INSTANCE}T_TMP_ACC_FND.FND1040_TRANS AS TRANS
ON  TRG.eff_to_dt = DATE '3500-12-31' /* Current effective record */
AND TRG.styl_wid = TRANS.styl_wid 
    
WHERE TRANS.styl_wid is NULL /* No existing or a deleted */
;

.IF ERRORCODE <> 0 THEN .QUIT 101


/* End of step */