/*
# ===============================================================================
#                      PRIMARK
#
# ===============================================================================
# ===============================================================================
# File Name           : OLR1001.100.TRANS.sql
# Pattern             : 
# Purpose             : Insertion in TRANS table
# Author              : TERADATA
# File Type           : SQL
# Creation Date       : 2025-07-20
# -------------------------------------------------------------------------------
# Change History :
# Ver  | Date        |  Modified By           |  Change Description
# -------------------------------------------------------------------------------
# Automatically generated by 10cents_table_generator
# 1.0  | 2025-07-20 | TERADATA               |  INITIAL CODE
# Build Time 20:03:48
# 1.0  | 2025-07-20 | TERADATA               |  INITIAL CODE
*/


DELETE FROM DW${INSTANCE}T_TMP_ACC_FND.FND1013_VALID
;

.IF ERRORCODE <> 0 THEN .QUIT 101

INSERT INTO DW${INSTANCE}T_TMP_ACC_FND.FND1013_VALID
(
    calendar_dt, 
    year_start_dt, 
    year_end_dt, 
    period_start_dt, 
    period_end_dt, 
    week_start_dt, 
    week_end_dt, 
    day_of_year_num, 
    day_of_period_num, 
    day_of_week_num, 
    week_of_year_num, 
    week_of_period_num, 
    period_of_year_num, 
    year_week, 
    year_period, 
    year_num, 
    ly_calendar_dt, 
    ly_year_start_dt, 
    ly_year_end_dt, 
    ly_period_start_dt, 
    ly_period_end_dt, 
    ly_week_start_dt, 
    ly_week_end_dt, 
    ly_day_of_year_num, 
    ly_day_of_period_num, 
    ly_day_of_week_num, 
    ly_week_of_year_num, 
    ly_week_of_period_num, 
    ly_period_of_year_num, 
    ly_year_week, 
    ly_year_period, 
    ly_year_num, 
    lly_calendar_dt, 
    lly_year_start_dt, 
    lly_year_end_dt, 
    lly_period_start_dt, 
    lly_period_end_dt, 
    lly_week_start_dt, 
    lly_week_end_dt, 
    lly_day_of_year_num, 
    lly_day_of_period_num, 
    lly_day_of_week_num, 
    lly_week_of_year_num, 
    lly_week_of_period_num, 
    lly_period_of_year_num, 
    lly_year_week, 
    lly_year_period, 
    lly_year_num, 
    llly_calendar_dt, 
    llly_year_start_dt, 
    llly_year_end_dt, 
    llly_period_start_dt, 
    llly_period_end_dt, 
    llly_week_start_dt, 
    llly_week_end_dt, 
    llly_day_of_year_num, 
    llly_day_of_period_num, 
    llly_day_of_week_num, 
    llly_week_of_year_num, 
    llly_week_of_period_num, 
    llly_period_of_year_num, 
    llly_year_week, 
    llly_year_period, 
    llly_year_num, 
    ny_calendar_dt, 
    ny_year_start_dt, 
    ny_year_end_dt, 
    ny_period_start_dt, 
    ny_period_end_dt, 
    ny_week_start_dt, 
    ny_week_end_dt, 
    ny_day_of_year_num, 
    ny_day_of_period_num, 
    ny_day_of_week_num, 
    ny_week_of_year_num, 
    ny_week_of_period_num, 
    ny_period_of_year_num, 
    ny_year_week, 
    ny_year_period, 
    ny_year_num, 
    /* Control Columnts */
    eff_from_dt,
    eff_to_dt,
    del_ind,
    run_id,
    update_run_id,
    job_id,
    update_job_id
)

SELECT
    TRANS.calendar_dt, 
    TRANS.year_start_dt, 
    TRANS.year_end_dt, 
    TRANS.period_start_dt, 
    TRANS.period_end_dt, 
    TRANS.week_start_dt, 
    TRANS.week_end_dt, 
    TRANS.day_of_year_num, 
    TRANS.day_of_period_num, 
    TRANS.day_of_week_num, 
    TRANS.week_of_year_num, 
    TRANS.week_of_period_num, 
    TRANS.period_of_year_num, 
    TRANS.year_week, 
    TRANS.year_period, 
    TRANS.year_num, 
    TRANS.ly_calendar_dt, 
    TRANS.ly_year_start_dt, 
    TRANS.ly_year_end_dt, 
    TRANS.ly_period_start_dt, 
    TRANS.ly_period_end_dt, 
    TRANS.ly_week_start_dt, 
    TRANS.ly_week_end_dt, 
    TRANS.ly_day_of_year_num, 
    TRANS.ly_day_of_period_num, 
    TRANS.ly_day_of_week_num, 
    TRANS.ly_week_of_year_num, 
    TRANS.ly_week_of_period_num, 
    TRANS.ly_period_of_year_num, 
    TRANS.ly_year_week, 
    TRANS.ly_year_period, 
    TRANS.ly_year_num, 
    TRANS.lly_calendar_dt, 
    TRANS.lly_year_start_dt, 
    TRANS.lly_year_end_dt, 
    TRANS.lly_period_start_dt, 
    TRANS.lly_period_end_dt, 
    TRANS.lly_week_start_dt, 
    TRANS.lly_week_end_dt, 
    TRANS.lly_day_of_year_num, 
    TRANS.lly_day_of_period_num, 
    TRANS.lly_day_of_week_num, 
    TRANS.lly_week_of_year_num, 
    TRANS.lly_week_of_period_num, 
    TRANS.lly_period_of_year_num, 
    TRANS.lly_year_week, 
    TRANS.lly_year_period, 
    TRANS.lly_year_num, 
    TRANS.llly_calendar_dt, 
    TRANS.llly_year_start_dt, 
    TRANS.llly_year_end_dt, 
    TRANS.llly_period_start_dt, 
    TRANS.llly_period_end_dt, 
    TRANS.llly_week_start_dt, 
    TRANS.llly_week_end_dt, 
    TRANS.llly_day_of_year_num, 
    TRANS.llly_day_of_period_num, 
    TRANS.llly_day_of_week_num, 
    TRANS.llly_week_of_year_num, 
    TRANS.llly_week_of_period_num, 
    TRANS.llly_period_of_year_num, 
    TRANS.llly_year_week, 
    TRANS.llly_year_period, 
    TRANS.llly_year_num, 
    TRANS.ny_calendar_dt, 
    TRANS.ny_year_start_dt, 
    TRANS.ny_year_end_dt, 
    TRANS.ny_period_start_dt, 
    TRANS.ny_period_end_dt, 
    TRANS.ny_week_start_dt, 
    TRANS.ny_week_end_dt, 
    TRANS.ny_day_of_year_num, 
    TRANS.ny_day_of_period_num, 
    TRANS.ny_day_of_week_num, 
    TRANS.ny_week_of_year_num, 
    TRANS.ny_week_of_period_num, 
    TRANS.ny_period_of_year_num, 
    TRANS.ny_year_week, 
    TRANS.ny_year_period, 
    TRANS.ny_year_num, 
    /* Control Columnts */
    date '${EFF_FROM}' AS eff_from_dt,
    DATE '9999-12-31' AS eff_to_dt,
    0 AS del_ind,
    ${RUNID} AS run_id,
    NULL AS update_run_id,
    '${JOB}' AS job_id,
    NULL AS update_job_id
FROM DW${INSTANCE}T_TMP_ACC_FND.FND1010_DW_FND_DATE_DIM AS TRANS
LEFT OUTER JOIN DW${INSTANCE}. AS TRG
ON  TRG.eff_to_dt = DATE '9999-12-31' /* Current effective record */
AND TRG.del_ind = 0 /* Not deleted */
AND TRG.calendar_dt = TRANS.SRC.calendar_dt 
    
WHERE (  /* Change detection */ 
    TRG.del_ind IS NULL /* No existing or a deleted */
OR TRG.year_start_dt <> TRANS.SRC.year_start_dt 
OR (TRG.year_start_dt IS NULL AND TRANS.SRC.year_start_dt IS NOT NULL)
OR (TRG.year_start_dt IS NOT NULL AND TRANS.SRC.year_start_dt IS NULL)
    
OR TRG.year_end_dt <> TRANS.SRC.year_end_dt 
OR (TRG.year_end_dt IS NULL AND TRANS.SRC.year_end_dt IS NOT NULL)
OR (TRG.year_end_dt IS NOT NULL AND TRANS.SRC.year_end_dt IS NULL)
    
OR TRG.period_start_dt <> TRANS.SRC.period_start_dt 
OR (TRG.period_start_dt IS NULL AND TRANS.SRC.period_start_dt IS NOT NULL)
OR (TRG.period_start_dt IS NOT NULL AND TRANS.SRC.period_start_dt IS NULL)
    
OR TRG.period_end_dt <> TRANS.SRC.period_end_dt 
OR (TRG.period_end_dt IS NULL AND TRANS.SRC.period_end_dt IS NOT NULL)
OR (TRG.period_end_dt IS NOT NULL AND TRANS.SRC.period_end_dt IS NULL)
    
OR TRG.week_start_dt <> TRANS.SRC.week_start_dt 
OR (TRG.week_start_dt IS NULL AND TRANS.SRC.week_start_dt IS NOT NULL)
OR (TRG.week_start_dt IS NOT NULL AND TRANS.SRC.week_start_dt IS NULL)
    
OR TRG.week_end_dt <> TRANS.SRC.week_end_dt 
OR (TRG.week_end_dt IS NULL AND TRANS.SRC.week_end_dt IS NOT NULL)
OR (TRG.week_end_dt IS NOT NULL AND TRANS.SRC.week_end_dt IS NULL)
    
OR TRG.day_of_year_num <> TRANS.SRC.day_of_year_num 
OR (TRG.day_of_year_num IS NULL AND TRANS.SRC.day_of_year_num IS NOT NULL)
OR (TRG.day_of_year_num IS NOT NULL AND TRANS.SRC.day_of_year_num IS NULL)
    
OR TRG.day_of_period_num <> TRANS.SRC.day_of_period_num 
OR (TRG.day_of_period_num IS NULL AND TRANS.SRC.day_of_period_num IS NOT NULL)
OR (TRG.day_of_period_num IS NOT NULL AND TRANS.SRC.day_of_period_num IS NULL)
    
OR TRG.day_of_week_num <> TRANS.SRC.day_of_week_num 
OR (TRG.day_of_week_num IS NULL AND TRANS.SRC.day_of_week_num IS NOT NULL)
OR (TRG.day_of_week_num IS NOT NULL AND TRANS.SRC.day_of_week_num IS NULL)
    
OR TRG.week_of_year_num <> TRANS.SRC.week_of_year_num 
OR (TRG.week_of_year_num IS NULL AND TRANS.SRC.week_of_year_num IS NOT NULL)
OR (TRG.week_of_year_num IS NOT NULL AND TRANS.SRC.week_of_year_num IS NULL)
    
OR TRG.week_of_period_num <> TRANS.SRC.week_of_period_num 
OR (TRG.week_of_period_num IS NULL AND TRANS.SRC.week_of_period_num IS NOT NULL)
OR (TRG.week_of_period_num IS NOT NULL AND TRANS.SRC.week_of_period_num IS NULL)
    
OR TRG.period_of_year_num <> TRANS.SRC.period_of_year_num 
OR (TRG.period_of_year_num IS NULL AND TRANS.SRC.period_of_year_num IS NOT NULL)
OR (TRG.period_of_year_num IS NOT NULL AND TRANS.SRC.period_of_year_num IS NULL)
    
OR TRG.year_week <> TRANS.SRC.year_week 
OR (TRG.year_week IS NULL AND TRANS.SRC.year_week IS NOT NULL)
OR (TRG.year_week IS NOT NULL AND TRANS.SRC.year_week IS NULL)
    
OR TRG.year_period <> TRANS.SRC.year_period 
OR (TRG.year_period IS NULL AND TRANS.SRC.year_period IS NOT NULL)
OR (TRG.year_period IS NOT NULL AND TRANS.SRC.year_period IS NULL)
    
OR TRG.year_num <> TRANS.SRC.year_num 
OR (TRG.year_num IS NULL AND TRANS.SRC.year_num IS NOT NULL)
OR (TRG.year_num IS NOT NULL AND TRANS.SRC.year_num IS NULL)
    
OR TRG.ly_calendar_dt <> TRANS.SRC.ly_calendar_dt 
OR (TRG.ly_calendar_dt IS NULL AND TRANS.SRC.ly_calendar_dt IS NOT NULL)
OR (TRG.ly_calendar_dt IS NOT NULL AND TRANS.SRC.ly_calendar_dt IS NULL)
    
OR TRG.ly_year_start_dt <> TRANS.SRC.ly_year_start_dt 
OR (TRG.ly_year_start_dt IS NULL AND TRANS.SRC.ly_year_start_dt IS NOT NULL)
OR (TRG.ly_year_start_dt IS NOT NULL AND TRANS.SRC.ly_year_start_dt IS NULL)
    
OR TRG.ly_year_end_dt <> TRANS.SRC.ly_year_end_dt 
OR (TRG.ly_year_end_dt IS NULL AND TRANS.SRC.ly_year_end_dt IS NOT NULL)
OR (TRG.ly_year_end_dt IS NOT NULL AND TRANS.SRC.ly_year_end_dt IS NULL)
    
OR TRG.ly_period_start_dt <> TRANS.SRC.ly_period_start_dt 
OR (TRG.ly_period_start_dt IS NULL AND TRANS.SRC.ly_period_start_dt IS NOT NULL)
OR (TRG.ly_period_start_dt IS NOT NULL AND TRANS.SRC.ly_period_start_dt IS NULL)
    
OR TRG.ly_period_end_dt <> TRANS.SRC.ly_period_end_dt 
OR (TRG.ly_period_end_dt IS NULL AND TRANS.SRC.ly_period_end_dt IS NOT NULL)
OR (TRG.ly_period_end_dt IS NOT NULL AND TRANS.SRC.ly_period_end_dt IS NULL)
    
OR TRG.ly_week_start_dt <> TRANS.SRC.ly_week_start_dt 
OR (TRG.ly_week_start_dt IS NULL AND TRANS.SRC.ly_week_start_dt IS NOT NULL)
OR (TRG.ly_week_start_dt IS NOT NULL AND TRANS.SRC.ly_week_start_dt IS NULL)
    
OR TRG.ly_week_end_dt <> TRANS.SRC.ly_week_end_dt 
OR (TRG.ly_week_end_dt IS NULL AND TRANS.SRC.ly_week_end_dt IS NOT NULL)
OR (TRG.ly_week_end_dt IS NOT NULL AND TRANS.SRC.ly_week_end_dt IS NULL)
    
OR TRG.ly_day_of_year_num <> TRANS.SRC.ly_day_of_year_num 
OR (TRG.ly_day_of_year_num IS NULL AND TRANS.SRC.ly_day_of_year_num IS NOT NULL)
OR (TRG.ly_day_of_year_num IS NOT NULL AND TRANS.SRC.ly_day_of_year_num IS NULL)
    
OR TRG.ly_day_of_period_num <> TRANS.SRC.ly_day_of_period_num 
OR (TRG.ly_day_of_period_num IS NULL AND TRANS.SRC.ly_day_of_period_num IS NOT NULL)
OR (TRG.ly_day_of_period_num IS NOT NULL AND TRANS.SRC.ly_day_of_period_num IS NULL)
    
OR TRG.ly_day_of_week_num <> TRANS.SRC.ly_day_of_week_num 
OR (TRG.ly_day_of_week_num IS NULL AND TRANS.SRC.ly_day_of_week_num IS NOT NULL)
OR (TRG.ly_day_of_week_num IS NOT NULL AND TRANS.SRC.ly_day_of_week_num IS NULL)
    
OR TRG.ly_week_of_year_num <> TRANS.SRC.ly_week_of_year_num 
OR (TRG.ly_week_of_year_num IS NULL AND TRANS.SRC.ly_week_of_year_num IS NOT NULL)
OR (TRG.ly_week_of_year_num IS NOT NULL AND TRANS.SRC.ly_week_of_year_num IS NULL)
    
OR TRG.ly_week_of_period_num <> TRANS.SRC.ly_week_of_period_num 
OR (TRG.ly_week_of_period_num IS NULL AND TRANS.SRC.ly_week_of_period_num IS NOT NULL)
OR (TRG.ly_week_of_period_num IS NOT NULL AND TRANS.SRC.ly_week_of_period_num IS NULL)
    
OR TRG.ly_period_of_year_num <> TRANS.SRC.ly_period_of_year_num 
OR (TRG.ly_period_of_year_num IS NULL AND TRANS.SRC.ly_period_of_year_num IS NOT NULL)
OR (TRG.ly_period_of_year_num IS NOT NULL AND TRANS.SRC.ly_period_of_year_num IS NULL)
    
OR TRG.ly_year_week <> TRANS.SRC.ly_year_week 
OR (TRG.ly_year_week IS NULL AND TRANS.SRC.ly_year_week IS NOT NULL)
OR (TRG.ly_year_week IS NOT NULL AND TRANS.SRC.ly_year_week IS NULL)
    
OR TRG.ly_year_period <> TRANS.SRC.ly_year_period 
OR (TRG.ly_year_period IS NULL AND TRANS.SRC.ly_year_period IS NOT NULL)
OR (TRG.ly_year_period IS NOT NULL AND TRANS.SRC.ly_year_period IS NULL)
    
OR TRG.ly_year_num <> TRANS.SRC.ly_year_num 
OR (TRG.ly_year_num IS NULL AND TRANS.SRC.ly_year_num IS NOT NULL)
OR (TRG.ly_year_num IS NOT NULL AND TRANS.SRC.ly_year_num IS NULL)
    
OR TRG.lly_calendar_dt <> TRANS.SRC.lly_calendar_dt 
OR (TRG.lly_calendar_dt IS NULL AND TRANS.SRC.lly_calendar_dt IS NOT NULL)
OR (TRG.lly_calendar_dt IS NOT NULL AND TRANS.SRC.lly_calendar_dt IS NULL)
    
OR TRG.lly_year_start_dt <> TRANS.SRC.lly_year_start_dt 
OR (TRG.lly_year_start_dt IS NULL AND TRANS.SRC.lly_year_start_dt IS NOT NULL)
OR (TRG.lly_year_start_dt IS NOT NULL AND TRANS.SRC.lly_year_start_dt IS NULL)
    
OR TRG.lly_year_end_dt <> TRANS.SRC.lly_year_end_dt 
OR (TRG.lly_year_end_dt IS NULL AND TRANS.SRC.lly_year_end_dt IS NOT NULL)
OR (TRG.lly_year_end_dt IS NOT NULL AND TRANS.SRC.lly_year_end_dt IS NULL)
    
OR TRG.lly_period_start_dt <> TRANS.SRC.lly_period_start_dt 
OR (TRG.lly_period_start_dt IS NULL AND TRANS.SRC.lly_period_start_dt IS NOT NULL)
OR (TRG.lly_period_start_dt IS NOT NULL AND TRANS.SRC.lly_period_start_dt IS NULL)
    
OR TRG.lly_period_end_dt <> TRANS.SRC.lly_period_end_dt 
OR (TRG.lly_period_end_dt IS NULL AND TRANS.SRC.lly_period_end_dt IS NOT NULL)
OR (TRG.lly_period_end_dt IS NOT NULL AND TRANS.SRC.lly_period_end_dt IS NULL)
    
OR TRG.lly_week_start_dt <> TRANS.SRC.lly_week_start_dt 
OR (TRG.lly_week_start_dt IS NULL AND TRANS.SRC.lly_week_start_dt IS NOT NULL)
OR (TRG.lly_week_start_dt IS NOT NULL AND TRANS.SRC.lly_week_start_dt IS NULL)
    
OR TRG.lly_week_end_dt <> TRANS.SRC.lly_week_end_dt 
OR (TRG.lly_week_end_dt IS NULL AND TRANS.SRC.lly_week_end_dt IS NOT NULL)
OR (TRG.lly_week_end_dt IS NOT NULL AND TRANS.SRC.lly_week_end_dt IS NULL)
    
OR TRG.lly_day_of_year_num <> TRANS.SRC.lly_day_of_year_num 
OR (TRG.lly_day_of_year_num IS NULL AND TRANS.SRC.lly_day_of_year_num IS NOT NULL)
OR (TRG.lly_day_of_year_num IS NOT NULL AND TRANS.SRC.lly_day_of_year_num IS NULL)
    
OR TRG.lly_day_of_period_num <> TRANS.SRC.lly_day_of_period_num 
OR (TRG.lly_day_of_period_num IS NULL AND TRANS.SRC.lly_day_of_period_num IS NOT NULL)
OR (TRG.lly_day_of_period_num IS NOT NULL AND TRANS.SRC.lly_day_of_period_num IS NULL)
    
OR TRG.lly_day_of_week_num <> TRANS.SRC.lly_day_of_week_num 
OR (TRG.lly_day_of_week_num IS NULL AND TRANS.SRC.lly_day_of_week_num IS NOT NULL)
OR (TRG.lly_day_of_week_num IS NOT NULL AND TRANS.SRC.lly_day_of_week_num IS NULL)
    
OR TRG.lly_week_of_year_num <> TRANS.SRC.lly_week_of_year_num 
OR (TRG.lly_week_of_year_num IS NULL AND TRANS.SRC.lly_week_of_year_num IS NOT NULL)
OR (TRG.lly_week_of_year_num IS NOT NULL AND TRANS.SRC.lly_week_of_year_num IS NULL)
    
OR TRG.lly_week_of_period_num <> TRANS.SRC.lly_week_of_period_num 
OR (TRG.lly_week_of_period_num IS NULL AND TRANS.SRC.lly_week_of_period_num IS NOT NULL)
OR (TRG.lly_week_of_period_num IS NOT NULL AND TRANS.SRC.lly_week_of_period_num IS NULL)
    
OR TRG.lly_period_of_year_num <> TRANS.SRC.lly_period_of_year_num 
OR (TRG.lly_period_of_year_num IS NULL AND TRANS.SRC.lly_period_of_year_num IS NOT NULL)
OR (TRG.lly_period_of_year_num IS NOT NULL AND TRANS.SRC.lly_period_of_year_num IS NULL)
    
OR TRG.lly_year_week <> TRANS.SRC.lly_year_week 
OR (TRG.lly_year_week IS NULL AND TRANS.SRC.lly_year_week IS NOT NULL)
OR (TRG.lly_year_week IS NOT NULL AND TRANS.SRC.lly_year_week IS NULL)
    
OR TRG.lly_year_period <> TRANS.SRC.lly_year_period 
OR (TRG.lly_year_period IS NULL AND TRANS.SRC.lly_year_period IS NOT NULL)
OR (TRG.lly_year_period IS NOT NULL AND TRANS.SRC.lly_year_period IS NULL)
    
OR TRG.lly_year_num <> TRANS.SRC.lly_year_num 
OR (TRG.lly_year_num IS NULL AND TRANS.SRC.lly_year_num IS NOT NULL)
OR (TRG.lly_year_num IS NOT NULL AND TRANS.SRC.lly_year_num IS NULL)
    
OR TRG.llly_calendar_dt <> TRANS.SRC.llly_calendar_dt 
OR (TRG.llly_calendar_dt IS NULL AND TRANS.SRC.llly_calendar_dt IS NOT NULL)
OR (TRG.llly_calendar_dt IS NOT NULL AND TRANS.SRC.llly_calendar_dt IS NULL)
    
OR TRG.llly_year_start_dt <> TRANS.SRC.llly_year_start_dt 
OR (TRG.llly_year_start_dt IS NULL AND TRANS.SRC.llly_year_start_dt IS NOT NULL)
OR (TRG.llly_year_start_dt IS NOT NULL AND TRANS.SRC.llly_year_start_dt IS NULL)
    
OR TRG.llly_year_end_dt <> TRANS.SRC.llly_year_end_dt 
OR (TRG.llly_year_end_dt IS NULL AND TRANS.SRC.llly_year_end_dt IS NOT NULL)
OR (TRG.llly_year_end_dt IS NOT NULL AND TRANS.SRC.llly_year_end_dt IS NULL)
    
OR TRG.llly_period_start_dt <> TRANS.SRC.llly_period_start_dt 
OR (TRG.llly_period_start_dt IS NULL AND TRANS.SRC.llly_period_start_dt IS NOT NULL)
OR (TRG.llly_period_start_dt IS NOT NULL AND TRANS.SRC.llly_period_start_dt IS NULL)
    
OR TRG.llly_period_end_dt <> TRANS.SRC.llly_period_end_dt 
OR (TRG.llly_period_end_dt IS NULL AND TRANS.SRC.llly_period_end_dt IS NOT NULL)
OR (TRG.llly_period_end_dt IS NOT NULL AND TRANS.SRC.llly_period_end_dt IS NULL)
    
OR TRG.llly_week_start_dt <> TRANS.SRC.llly_week_start_dt 
OR (TRG.llly_week_start_dt IS NULL AND TRANS.SRC.llly_week_start_dt IS NOT NULL)
OR (TRG.llly_week_start_dt IS NOT NULL AND TRANS.SRC.llly_week_start_dt IS NULL)
    
OR TRG.llly_week_end_dt <> TRANS.SRC.llly_week_end_dt 
OR (TRG.llly_week_end_dt IS NULL AND TRANS.SRC.llly_week_end_dt IS NOT NULL)
OR (TRG.llly_week_end_dt IS NOT NULL AND TRANS.SRC.llly_week_end_dt IS NULL)
    
OR TRG.llly_day_of_year_num <> TRANS.SRC.llly_day_of_year_num 
OR (TRG.llly_day_of_year_num IS NULL AND TRANS.SRC.llly_day_of_year_num IS NOT NULL)
OR (TRG.llly_day_of_year_num IS NOT NULL AND TRANS.SRC.llly_day_of_year_num IS NULL)
    
OR TRG.llly_day_of_period_num <> TRANS.SRC.llly_day_of_period_num 
OR (TRG.llly_day_of_period_num IS NULL AND TRANS.SRC.llly_day_of_period_num IS NOT NULL)
OR (TRG.llly_day_of_period_num IS NOT NULL AND TRANS.SRC.llly_day_of_period_num IS NULL)
    
OR TRG.llly_day_of_week_num <> TRANS.SRC.llly_day_of_week_num 
OR (TRG.llly_day_of_week_num IS NULL AND TRANS.SRC.llly_day_of_week_num IS NOT NULL)
OR (TRG.llly_day_of_week_num IS NOT NULL AND TRANS.SRC.llly_day_of_week_num IS NULL)
    
OR TRG.llly_week_of_year_num <> TRANS.SRC.llly_week_of_year_num 
OR (TRG.llly_week_of_year_num IS NULL AND TRANS.SRC.llly_week_of_year_num IS NOT NULL)
OR (TRG.llly_week_of_year_num IS NOT NULL AND TRANS.SRC.llly_week_of_year_num IS NULL)
    
OR TRG.llly_week_of_period_num <> TRANS.SRC.llly_week_of_period_num 
OR (TRG.llly_week_of_period_num IS NULL AND TRANS.SRC.llly_week_of_period_num IS NOT NULL)
OR (TRG.llly_week_of_period_num IS NOT NULL AND TRANS.SRC.llly_week_of_period_num IS NULL)
    
OR TRG.llly_period_of_year_num <> TRANS.SRC.llly_period_of_year_num 
OR (TRG.llly_period_of_year_num IS NULL AND TRANS.SRC.llly_period_of_year_num IS NOT NULL)
OR (TRG.llly_period_of_year_num IS NOT NULL AND TRANS.SRC.llly_period_of_year_num IS NULL)
    
OR TRG.llly_year_week <> TRANS.SRC.llly_year_week 
OR (TRG.llly_year_week IS NULL AND TRANS.SRC.llly_year_week IS NOT NULL)
OR (TRG.llly_year_week IS NOT NULL AND TRANS.SRC.llly_year_week IS NULL)
    
OR TRG.llly_year_period <> TRANS.SRC.llly_year_period 
OR (TRG.llly_year_period IS NULL AND TRANS.SRC.llly_year_period IS NOT NULL)
OR (TRG.llly_year_period IS NOT NULL AND TRANS.SRC.llly_year_period IS NULL)
    
OR TRG.llly_year_num <> TRANS.SRC.llly_year_num 
OR (TRG.llly_year_num IS NULL AND TRANS.SRC.llly_year_num IS NOT NULL)
OR (TRG.llly_year_num IS NOT NULL AND TRANS.SRC.llly_year_num IS NULL)
    
OR TRG.ny_calendar_dt <> TRANS.SRC.ny_calendar_dt 
OR (TRG.ny_calendar_dt IS NULL AND TRANS.SRC.ny_calendar_dt IS NOT NULL)
OR (TRG.ny_calendar_dt IS NOT NULL AND TRANS.SRC.ny_calendar_dt IS NULL)
    
OR TRG.ny_year_start_dt <> TRANS.SRC.ny_year_start_dt 
OR (TRG.ny_year_start_dt IS NULL AND TRANS.SRC.ny_year_start_dt IS NOT NULL)
OR (TRG.ny_year_start_dt IS NOT NULL AND TRANS.SRC.ny_year_start_dt IS NULL)
    
OR TRG.ny_year_end_dt <> TRANS.SRC.ny_year_end_dt 
OR (TRG.ny_year_end_dt IS NULL AND TRANS.SRC.ny_year_end_dt IS NOT NULL)
OR (TRG.ny_year_end_dt IS NOT NULL AND TRANS.SRC.ny_year_end_dt IS NULL)
    
OR TRG.ny_period_start_dt <> TRANS.SRC.ny_period_start_dt 
OR (TRG.ny_period_start_dt IS NULL AND TRANS.SRC.ny_period_start_dt IS NOT NULL)
OR (TRG.ny_period_start_dt IS NOT NULL AND TRANS.SRC.ny_period_start_dt IS NULL)
    
OR TRG.ny_period_end_dt <> TRANS.SRC.ny_period_end_dt 
OR (TRG.ny_period_end_dt IS NULL AND TRANS.SRC.ny_period_end_dt IS NOT NULL)
OR (TRG.ny_period_end_dt IS NOT NULL AND TRANS.SRC.ny_period_end_dt IS NULL)
    
OR TRG.ny_week_start_dt <> TRANS.SRC.ny_week_start_dt 
OR (TRG.ny_week_start_dt IS NULL AND TRANS.SRC.ny_week_start_dt IS NOT NULL)
OR (TRG.ny_week_start_dt IS NOT NULL AND TRANS.SRC.ny_week_start_dt IS NULL)
    
OR TRG.ny_week_end_dt <> TRANS.SRC.ny_week_end_dt 
OR (TRG.ny_week_end_dt IS NULL AND TRANS.SRC.ny_week_end_dt IS NOT NULL)
OR (TRG.ny_week_end_dt IS NOT NULL AND TRANS.SRC.ny_week_end_dt IS NULL)
    
OR TRG.ny_day_of_year_num <> TRANS.SRC.ny_day_of_year_num 
OR (TRG.ny_day_of_year_num IS NULL AND TRANS.SRC.ny_day_of_year_num IS NOT NULL)
OR (TRG.ny_day_of_year_num IS NOT NULL AND TRANS.SRC.ny_day_of_year_num IS NULL)
    
OR TRG.ny_day_of_period_num <> TRANS.SRC.ny_day_of_period_num 
OR (TRG.ny_day_of_period_num IS NULL AND TRANS.SRC.ny_day_of_period_num IS NOT NULL)
OR (TRG.ny_day_of_period_num IS NOT NULL AND TRANS.SRC.ny_day_of_period_num IS NULL)
    
OR TRG.ny_day_of_week_num <> TRANS.SRC.ny_day_of_week_num 
OR (TRG.ny_day_of_week_num IS NULL AND TRANS.SRC.ny_day_of_week_num IS NOT NULL)
OR (TRG.ny_day_of_week_num IS NOT NULL AND TRANS.SRC.ny_day_of_week_num IS NULL)
    
OR TRG.ny_week_of_year_num <> TRANS.SRC.ny_week_of_year_num 
OR (TRG.ny_week_of_year_num IS NULL AND TRANS.SRC.ny_week_of_year_num IS NOT NULL)
OR (TRG.ny_week_of_year_num IS NOT NULL AND TRANS.SRC.ny_week_of_year_num IS NULL)
    
OR TRG.ny_week_of_period_num <> TRANS.SRC.ny_week_of_period_num 
OR (TRG.ny_week_of_period_num IS NULL AND TRANS.SRC.ny_week_of_period_num IS NOT NULL)
OR (TRG.ny_week_of_period_num IS NOT NULL AND TRANS.SRC.ny_week_of_period_num IS NULL)
    
OR TRG.ny_period_of_year_num <> TRANS.SRC.ny_period_of_year_num 
OR (TRG.ny_period_of_year_num IS NULL AND TRANS.SRC.ny_period_of_year_num IS NOT NULL)
OR (TRG.ny_period_of_year_num IS NOT NULL AND TRANS.SRC.ny_period_of_year_num IS NULL)
    
OR TRG.ny_year_week <> TRANS.SRC.ny_year_week 
OR (TRG.ny_year_week IS NULL AND TRANS.SRC.ny_year_week IS NOT NULL)
OR (TRG.ny_year_week IS NOT NULL AND TRANS.SRC.ny_year_week IS NULL)
    
OR TRG.ny_year_period <> TRANS.SRC.ny_year_period 
OR (TRG.ny_year_period IS NULL AND TRANS.SRC.ny_year_period IS NOT NULL)
OR (TRG.ny_year_period IS NOT NULL AND TRANS.SRC.ny_year_period IS NULL)
    
OR TRG.ny_year_num <> TRANS.SRC.ny_year_num 
OR (TRG.ny_year_num IS NULL AND TRANS.SRC.ny_year_num IS NOT NULL)
OR (TRG.ny_year_num IS NOT NULL AND TRANS.SRC.ny_year_num IS NULL)
    
) /* end of change detection */

;

.IF ERRORCODE <> 0 THEN .QUIT 101

/* End of INSERT statement */
END TRANSACTION
;
.IF ERRORCODE <> 0 THEN .QUIT 101



/* End of step */