/*
# ===============================================================================
#                      PRIMARK
#
# ===============================================================================
# ===============================================================================
# File Name           : FND2203.300.VALIDATE.sql
# Pattern             : 
# Purpose             : Validation Step
# Author              : TERADATA
# File Type           : SQL
# Creation Date       : 2025-08-07
# -------------------------------------------------------------------------------
# Change History :
# Ver  | Date        |  Modified By           |  Change Description
# -------------------------------------------------------------------------------
# Automatically generated by 10cents_table_generator
# 1.0  | 2025-08-07 | TERADATA               |  INITIAL CODE
# Build Time 16:22:11
# 1.0  | 2025-08-07 | TERADATA               |  INITIAL CODE
# Note: This step will perform validation checks on the target table.
# The general approach is to have test query in a CTE (Common Table Expression)
# and then return a subset of the rows in error
# the job will fail if ther are any rows returned
# ===============================================================================
*/

-- =============================================================================
-- Script Name: Duplicate Primary Key Check
-- Description: This script checks for duplicate records in the staging table
--              'DW${INSTANCE}T_TMP_ACC_FND.FND_SLS_FCT_01_FCT_STG' based on the
--              composite primary key (business_date, location_id, item_id).
--              It will exit with an error code if duplicates are found.
-- =============================================================================
-- Use a Common Table Expression (CTE) to identify duplicate records.
WITH TST AS (
    SELECT
        business_date,
        location_id,
        item_id,
        COUNT(*) AS dupl_count
    FROM
        DW${INSTANCE}T_TMP_ACC_FND.FND_SLS_FCT_01_FCT_STG
    GROUP BY
        -- Group by the columns that form the unique key to find duplicates.
        business_date,
        location_id,
        item_id
    HAVING
        -- Filter for groups with more than one record, which indicates a duplicate.
        dupl_count > 1
)
-- Select the top 10 duplicate records to display as a sample.
SELECT TOP 10
    'Duplicate count check' AS Error_Desc,
    TST.* -- Select all columns from the CTE
FROM
    TST
ORDER BY
    -- Order by location_id to make the output consistent.
    dupl_count DESC
;
-- =============================================================================
-- BTEQ Control Logic (Teradata Specific)
-- =============================================================================
-- Check the error code from the last SQL statement.
-- If ERRORCODE is not 0, it means the SELECT statement failed for some reason.
.IF ERRORCODE <> 0 THEN .QUIT 101
-- Check the activity count from the last SQL statement.
-- If ACTIVITYCOUNT is not 0, it means our query found and returned duplicate rows.
-- The script then quits with a specific error code (102) to signal this failure.
.IF ACTIVITYCOUNT <> 0 THEN .QUIT 102

.IF ERRORCODE <> 0 THEN .QUIT 101

/* End of step */