/*
# ===============================================================================
#                      PRIMARK
#
# ===============================================================================
# ===============================================================================
# File Name           : FND2204.300.TARGET.sql
# Pattern             : 
# Purpose             : Trans Bespoke step
# Author              : TERADATA
# File Type           : SQL
# Creation Date       : 2025-08-07
# -------------------------------------------------------------------------------
# Change History :
# Ver  | Date        |  Modified By           |  Change Description
# -------------------------------------------------------------------------------
# Automatically generated by 10cents_table_generator
# 1.0  | 2025-08-07 | TERADATA               |  INITIAL CODE
# Build Time 16:29:09
# 1.0  | 2025-08-07 | TERADATA               |  INITIAL CODE
*/

/*
This MERGE statement updates the target pivot table (FND_SLS_FCT_PVT_STG)
from the source staging table (FND_SLS_FCT_01_FCT_STG).
Key Logic:
1. Records are matched on business_date, location_id, and item_id.
2. WHEN MATCHED:
   - The fct_src_map is updated using a bitwise OR (BITOR).
   - This combines the bitmask from the target with the bitmask from the source,
     preserving a history of all data sources that have contributed to the record.
     For example, if T.fct_src_map is 1 (binary 0001) and S.fct_src_map is 2 (binary 0010),
     the result will be 3 (binary 0011).
3. WHEN NOT MATCHED:
   - A new record is inserted into the target table with the data from the source.
*/
MERGE INTO DW${INSTANCE}T_TMP_ACC_FND.FND_SLS_FCT_PVT_STG AS T
USING DW${INSTANCE}T_TMP_ACC_FND.FND_SLS_FCT_01_FCT_STG AS S
   ON T.business_date = S.business_date
  AND T.location_id = S.location_id
  AND T.item_id = S.item_id
WHEN MATCHED THEN
   UPDATE SET
      fct_src_map = BITOR(T.fct_src_map, S.fct_src_map)
WHEN NOT MATCHED THEN
   INSERT (
      business_date,
      location_id,
      item_id,
      fct_src_map
   )
   VALUES (
      S.business_date,
      S.location_id,
      S.item_id,
      S.fct_src_map
   );

.IF ERRORCODE <> 0 THEN .QUIT 101



/* End of step */