/*
# ===============================================================================
#                      PRIMARK
#
# ===============================================================================
# ===============================================================================
# File Name           : FND2106.310.VALIDATE.sql
# Pattern             : 
# Purpose             : Validation Step
# Author              : TERADATA
# File Type           : SQL
# Creation Date       : 2025-08-07
# -------------------------------------------------------------------------------
# Change History :
# Ver  | Date        |  Modified By           |  Change Description
# -------------------------------------------------------------------------------
# Automatically generated by 10cents_table_generator
# 1.0  | 2025-08-07 | TERADATA               |  INITIAL CODE
# Build Time 13:26:12
# 1.0  | 2025-08-07 | TERADATA               |  INITIAL CODE
# Note: This step will perform validation checks on the target table.
# The general approach is to have test query in a CTE (Common Table Expression)
# and then return a subset of the rows in error
# the job will fail if ther are any rows returned
# ===============================================================================
*/



.IF ERRORCODE <> 0 THEN .QUIT 101

/* End of step */