/*
# ===============================================================================
#                      PRIMARK
#
# ===============================================================================
# ===============================================================================
# File Name           : FND2101.300.TARGET.sql
# Pattern             : 
# Purpose             : Delete from table
# Author              : TERADATA
# File Type           : SQL
# Creation Date       : 2025-08-08
# -------------------------------------------------------------------------------
# Change History :
# Ver  | Date        |  Modified By           |  Change Description
# -------------------------------------------------------------------------------
# Automatically generated by 10cents_table_generator
# 1.0  | 2025-08-08 | TERADATA               |  INITIAL CODE
# Build Time 12:05:55
# 1.0  | 2025-08-08 | TERADATA               |  INITIAL CODE
*/


DELETE FROM DW${INSTANCE}T_TMP_ACC_FND.FND_STK_FCT_PVT_STG
;

.IF ERRORCODE <> 0 THEN .QUIT 101




/* End of step */