/*
# ===============================================================================
#                      PRIMARK
#
# ===============================================================================
# ===============================================================================
# File Name           : OLR1001.100.TRANS.sql
# Pattern             : 
# Purpose             : Insertion in TRANS table
# Author              : TERADATA
# File Type           : SQL
# Creation Date       : 2025-07-19
# -------------------------------------------------------------------------------
# Change History :
# Ver  | Date        |  Modified By           |  Change Description
# -------------------------------------------------------------------------------
# Automatically generated by 10cents_table_generator
# 1.0  | 2025-07-19 | TERADATA               |  INITIAL CODE
# Build Time 23:01:00
# 1.0  | 2025-07-19 | TERADATA               |  INITIAL CODE
*/


DELETE FROM DWT04T_TMP_ACC_FND.FND1010_DW_FND_DATE_DIM
;
-------------------------------------------------------------------------------------

-- EXECUTED SUCCESSFULLY
