/*
# ===============================================================================
#                      PRIMARK
#
# ===============================================================================
# ===============================================================================
# File Name           : OLR1001.100.TRANS.sql
# Pattern             : 
# Purpose             : Insertion in TRANS table
# Author              : TERADATA
# File Type           : SQL
# Creation Date       : 2025-07-24
# -------------------------------------------------------------------------------
# Change History :
# Ver  | Date        |  Modified By           |  Change Description
# -------------------------------------------------------------------------------
# Automatically generated by 10cents_table_generator
# 1.0  | 2025-07-24 | TERADATA               |  INITIAL CODE
# Build Time 08:26:58
# 1.0  | 2025-07-24 | TERADATA               |  INITIAL CODE
*/


DELETE FROM DWT04T_TMP_ACC_FND.FND1040_VALID
;
-------------------------------------------------------------------------------------

-- EXECUTED SUCCESSFULLY
-- ROW COUNT: 1411290
