/*
# ===============================================================================
#                      PRIMARK
#
# ===============================================================================
# ===============================================================================
# File Name           : OLR1001.100.TRANS.sql
# Pattern             : 
# Purpose             : Insertion in TRANS table
# Author              : TERADATA
# File Type           : SQL
# Creation Date       : 2025-07-20
# -------------------------------------------------------------------------------
# Change History :
# Ver  | Date        |  Modified By           |  Change Description
# -------------------------------------------------------------------------------
# Automatically generated by 10cents_table_generator
# 1.0  | 2025-07-20 | TERADATA               |  INITIAL CODE
# Build Time 14:51:29
# 1.0  | 2025-07-20 | TERADATA               |  INITIAL CODE
*/

--BEGIN TRANSACTION
;
-------------------------------------------------------------------------------------

-- EXECUTED SUCCESSFULLY
-- ROW COUNT: 0
