/*
# ===============================================================================
#                      PRIMARK
#
# ===============================================================================
# ===============================================================================
# File Name           : FND2201.300.TARGET.sql
# Pattern             : 
# Purpose             : Delete from table
# Author              : TERADATA
# File Type           : SQL
# Creation Date       : 2025-08-05
# -------------------------------------------------------------------------------
# Change History :
# Ver  | Date        |  Modified By           |  Change Description
# -------------------------------------------------------------------------------
# Automatically generated by 10cents_table_generator
# 1.0  | 2025-08-05 | TERADATA               |  INITIAL CODE
# Build Time 08:17:47
# 1.0  | 2025-08-05 | TERADATA               |  INITIAL CODE
*/


DELETE FROM DWT04T_TMP_ACC_FND.FND_SLS_FCT_PVT_STG
;

--.IF ERRORCODE <> 0 THEN .QUIT 101





/* Collect statistics for the table */
COLLECT STATISTICS COLUMN(business_date,location_id,item_id) ON DWT04T_TMP_ACC_FND.FND_SLS_FCT_PVT_STG
;
--.IF ERRORCODE <> 0 THEN .QUIT 101


/* End of step */