#!/usr/bin/ksh
# ===============================================================================
#                      PRIMARK
#
# ===============================================================================
# ===============================================================================
# File Name           : FND2106.job
# Pattern             : Validation
# Purpose             :This is a sample job description.
# Author              : Mr Primark
# File Type           : JOB
# Creation Date       : 2025-08-10 
# Build Time          : 2025-08-10 20:32:39
# -------------------------------------------------------------------------------
# Change History :
# Ver  | Date        |  Modified By           |  Change Description
# -------------------------------------------------------------------------------
# 0.0  | 2025-08-10 |  Mr Primark              |  INITIAL VERSION
# ===============================================================================

FPATH=$FPATH:$HOME/includes
JOB=

echo ---------------------------------------
echo JOB=${JOB:?}
echo ---------------------------------------


## job specific

SKIP_STEPS_CONTROL=1
INSERTED_STAGING=0
REJECTED_STAGING=0
DUPLICATE_STAGING=0
INSERTED_TARGET=0
REJECTED_TARGET=0
DUPLICATE_TARGET=0


tjc_stepout -e
tjc_onerror "tjc_alert -u '${LOGON}' -s '${SERVER}' -G TJC_${INSTANCE}_ALERT"
tjc_ontimeout "tjc_alert -u '${LOGON}' -s '${SERVER}' -G TJC_${INSTANCE}_ALERT  > /dev/null 2>&1"
tjc_stepout -e
tjc_onerror "tjc_alert -u '${LOGON}' -s '${SERVER}' -G TJC_${INSTANCE}_ALERT"
tjc_ontimeout "tjc_alert -u '${LOGON}' -s '${SERVER}' -G TJC_${INSTANCE}_ALERT  > /dev/null 2>&1"

#-------------------------------------------------------------------------------
# Step 001 : Log start of job by running FND_JobStart.sql
#-------------------------------------------------------------------------------

step 001 Bteq -s "${SERVER:?}" -u "${LOGON:?}" -v MET_V="${MET_V}" \
              -v STEP_NO=001 \
              -v INSTANCE="${INSTANCE:?}" \
              -v JOB="${JOB:?}" ${STEP_DIR:?}/FND_JobStart.sql

#-------------------------------------------------------------------------------
# Step 003 : Get the RUNID parameter
#-------------------------------------------------------------------------------

# need to grab the run id so we can append it to the report files to make it unique
step 003 Bteq -s "${SERVER:?}" -u "${LOGON:?}" \
              -v STEP_NO="003" -v INSTANCE="${INSTANCE:?}" \
              -v MET_V="${MET_V:?}" -v INSTANCE="${INSTANCE:?}" \
              -v JOB=${JOB:?} ${STEP_DIR:?}/FND_GetRunId.sql

RUN_ID=$(tjc_stepout -l | awk '/^RUN_ID;/{print $2}')



#-------------------------------------------------------------------------------
# Step 020 : Get the parameters
#-------------------------------------------------------------------------------

# Set default time parameter
JOB_PARAM_TS_FORMAT=${JOB_PARAM_TS_FORMAT:="YYYY-MM-DD HH:MI:SS"}
# Set Work file
JOB_PARAM_WORKFILE=$(tjc_workfile -c JOB_PARAM)
step 020 Bteq -s "${SERVER:?}" -u "${LOGON:?}" -v MET_V="${MET_V}" \
              -v JOB_PARAM_DT_FORMAT="${JOB_PARAM_DT_FORMAT:=YYYY-MM-DD}"\
              -v JOB_PARAM_DT_ALT_FORMAT="${JOB_PARAM_DT_FORMAT:=IGNORE}"\
              -v JOB_PARAM_TS_FORMAT="${JOB_PARAM_TS_FORMAT}"\
              -v JOB_PARAM_INT_FORMAT="${JOB_PARAM_INT_FORMAT:=TM}"\
              -v STEP_NO="020" -v INSTANCE="${INSTANCE:?}" \
              -v JOB=${JOB:?} ${STEP_DIR:?}/FND_GetALLParams.sql

tjc_stepout -l|grep ^\!|cut -d\! -f2 >${JOB_PARAM_WORKFILE}

# Set environment parameters
. ${JOB_PARAM_WORKFILE}

# Overwrite parameters with command line
export $(MY_TMP=${TJC_OPTIONS//-v };echo ${MY_TMP//\"})


#-------------------------------------------------------------------------------
# Step 025 : Get Stream
#-------------------------------------------------------------------------------


# Set Work file
STREAM_PARAM_WORKFILE=$(tjc_workfile -c JOB_PARAM)
step 025 Bteq -s "${SERVER:?}" -u "${LOGON:?}" -v MET_V="${MET_V}" \
              -v STEP_NO="025" \
              -v INSTANCE="${INSTANCE:?}" \
              -v STREAMID="${STREAMID:?}" \
              -v JOB=${JOB:?} ${STEP_DIR:?}/FND_GetStream.sql

tjc_stepout -l|grep ^\!|cut -d\! -f2 >${STREAM_PARAM_WORKFILE}

# Set environment parameters
. ${STREAM_PARAM_WORKFILE}

# Overwrite parameters with command line
export $(MY_TMP=${TJC_OPTIONS//-v };echo ${MY_TMP//\"})


#-------------------------------------------------------------------------------
# Step 030 : Get Load Token
#-------------------------------------------------------------------------------


# Set Work file
LDTK_PARAM_WORKFILE=$(tjc_workfile -c JOB_PARAM)
step 030 Bteq -s "${SERVER:?}" -u "${LOGON:?}" -v MET_V="${MET_V}" \
              -v STEP_NO="030" \
              -v INSTANCE="${INSTANCE:?}" \
              -v STREAMID="${STREAMID:?}" \
              -v LDTK_DATE="${LDTK_DATE:?}" \
              -v LDTK_PREV_DATE="${LDTK_PREV_DATE:?}" \
              -v LDTK_NEXT_DATE="${LDTK_NEXT_DATE:?}" \
              -v JOB=${JOB:?} ${STEP_DIR:?}/FND_GetLoadToken.sql

tjc_stepout -l|grep ^\!|cut -d\! -f2 >${LDTK_PARAM_WORKFILE}

# Set environment parameters
. ${LDTK_PARAM_WORKFILE}

# Overwrite parameters with command line
export $(MY_TMP=${TJC_OPTIONS//-v };echo ${MY_TMP//\"})


#-------------------------------------------------------------------------------
# Step 300 : Validate that there are no duplicates on primary index
#-------------------------------------------------------------------------------

step 300 Bteq -s "${SERVER:?}" -u "${LOGON:?}" \
              -v MET_V="${MET_V}" \
              -v JOB="${JOB:?}" \
              -v STEP_NO=300 \
              -v INSTANCE="${INSTANCE:?}" \
              -v STREAMID="${STREAMID:?}" \
              -v LDTK_DATE="${LDTK_DATE:?}" \
              -v LDTK_PREV_DATE="${LDTK_PREV_DATE:?}" \
              -v LDTK_NEXT_DATE="${LDTK_NEXT_DATE:?}" \
              -v RUN_ID="${RUN_ID:?}" \
              -v RUNID="${RUN_ID:?}" \
              -v EFF_FROM_DT="${EFF_FROM_DT:?}" \
              -v CALENDAR_DT="${CALENDAR_DT:?}" \
              -v YEAR_START_DT="${YEAR_START_DT:?}" \
              -v YEAR_END_DT="${YEAR_END_DT:?}" \
              -v PERIOD_START_DT="${PERIOD_START_DT:?}" \
              -v PERIOD_END_DT="${PERIOD_END_DT:?}" \
              -v WEEK_START_DT="${WEEK_START_DT:?}" \
              -v WEEK_END_DT="${WEEK_END_DT:?}" \
              -v DAY_OF_YEAR_NUM="${DAY_OF_YEAR_NUM:?}" \
              -v DAY_OF_PERIOD_NUM="${DAY_OF_PERIOD_NUM:?}" \
              -v DAY_OF_WEEK_NUM="${DAY_OF_WEEK_NUM:?}" \
              -v WEEK_OF_YEAR_NUM="${WEEK_OF_YEAR_NUM:?}" \
              -v WEEK_OF_PERIOD_NUM="${WEEK_OF_PERIOD_NUM:?}" \
              -v PERIOD_OF_YEAR_NUM="${PERIOD_OF_YEAR_NUM:?}" \
              -v YEAR_WEEK="${YEAR_WEEK:?}" \
              -v YEAR_PERIOD="${YEAR_PERIOD:?}" \
              -v YEAR_NUM="${YEAR_NUM:?}" \
              -v SEASON_CODE="${SEASON_CODE:?}" \
              -v SEASON_NAME="${SEASON_NAME:?}" \
              -v SEASON_DESCRIPTION="${SEASON_DESCRIPTION:?}" \
              -v LY_CALENDAR_DT="${LY_CALENDAR_DT:?}" \
              -v LY_YEAR_START_DT="${LY_YEAR_START_DT:?}" \
              -v LY_YEAR_END_DT="${LY_YEAR_END_DT:?}" \
              -v LY_PERIOD_START_DT="${LY_PERIOD_START_DT:?}" \
              -v LY_PERIOD_END_DT="${LY_PERIOD_END_DT:?}" \
              -v LY_WEEK_START_DT="${LY_WEEK_START_DT:?}" \
              -v LY_WEEK_END_DT="${LY_WEEK_END_DT:?}" \
              -v LY_DAY_OF_YEAR_NUM="${LY_DAY_OF_YEAR_NUM:?}" \
              -v LY_DAY_OF_PERIOD_NUM="${LY_DAY_OF_PERIOD_NUM:?}" \
              -v LY_DAY_OF_WEEK_NUM="${LY_DAY_OF_WEEK_NUM:?}" \
              -v LY_WEEK_OF_YEAR_NUM="${LY_WEEK_OF_YEAR_NUM:?}" \
              -v LY_WEEK_OF_PERIOD_NUM="${LY_WEEK_OF_PERIOD_NUM:?}" \
              -v LY_PERIOD_OF_YEAR_NUM="${LY_PERIOD_OF_YEAR_NUM:?}" \
              -v LY_YEAR_WEEK="${LY_YEAR_WEEK:?}" \
              -v LY_YEAR_PERIOD="${LY_YEAR_PERIOD:?}" \
              -v LY_YEAR_NUM="${LY_YEAR_NUM:?}" \
              -v LLY_CALENDAR_DT="${LLY_CALENDAR_DT:?}" \
              -v LLY_YEAR_START_DT="${LLY_YEAR_START_DT:?}" \
              -v LLY_YEAR_END_DT="${LLY_YEAR_END_DT:?}" \
              -v LLY_PERIOD_START_DT="${LLY_PERIOD_START_DT:?}" \
              -v LLY_PERIOD_END_DT="${LLY_PERIOD_END_DT:?}" \
              -v LLY_WEEK_START_DT="${LLY_WEEK_START_DT:?}" \
              -v LLY_WEEK_END_DT="${LLY_WEEK_END_DT:?}" \
              -v LLY_DAY_OF_YEAR_NUM="${LLY_DAY_OF_YEAR_NUM:?}" \
              -v LLY_DAY_OF_PERIOD_NUM="${LLY_DAY_OF_PERIOD_NUM:?}" \
              -v LLY_DAY_OF_WEEK_NUM="${LLY_DAY_OF_WEEK_NUM:?}" \
              -v LLY_WEEK_OF_YEAR_NUM="${LLY_WEEK_OF_YEAR_NUM:?}" \
              -v LLY_WEEK_OF_PERIOD_NUM="${LLY_WEEK_OF_PERIOD_NUM:?}" \
              -v LLY_PERIOD_OF_YEAR_NUM="${LLY_PERIOD_OF_YEAR_NUM:?}" \
              -v LLY_YEAR_WEEK="${LLY_YEAR_WEEK:?}" \
              -v LLY_YEAR_PERIOD="${LLY_YEAR_PERIOD:?}" \
              -v LLY_YEAR_NUM="${LLY_YEAR_NUM:?}" \
              -v LLLY_CALENDAR_DT="${LLLY_CALENDAR_DT:?}" \
              -v LLLY_YEAR_START_DT="${LLLY_YEAR_START_DT:?}" \
              -v LLLY_YEAR_END_DT="${LLLY_YEAR_END_DT:?}" \
              -v LLLY_PERIOD_START_DT="${LLLY_PERIOD_START_DT:?}" \
              -v LLLY_PERIOD_END_DT="${LLLY_PERIOD_END_DT:?}" \
              -v LLLY_WEEK_START_DT="${LLLY_WEEK_START_DT:?}" \
              -v LLLY_WEEK_END_DT="${LLLY_WEEK_END_DT:?}" \
              -v LLLY_DAY_OF_YEAR_NUM="${LLLY_DAY_OF_YEAR_NUM:?}" \
              -v LLLY_DAY_OF_PERIOD_NUM="${LLLY_DAY_OF_PERIOD_NUM:?}" \
              -v LLLY_DAY_OF_WEEK_NUM="${LLLY_DAY_OF_WEEK_NUM:?}" \
              -v LLLY_WEEK_OF_YEAR_NUM="${LLLY_WEEK_OF_YEAR_NUM:?}" \
              -v LLLY_WEEK_OF_PERIOD_NUM="${LLLY_WEEK_OF_PERIOD_NUM:?}" \
              -v LLLY_PERIOD_OF_YEAR_NUM="${LLLY_PERIOD_OF_YEAR_NUM:?}" \
              -v LLLY_YEAR_WEEK="${LLLY_YEAR_WEEK:?}" \
              -v LLLY_YEAR_PERIOD="${LLLY_YEAR_PERIOD:?}" \
              -v LLLY_YEAR_NUM="${LLLY_YEAR_NUM:?}" \
              -v NY_CALENDAR_DT="${NY_CALENDAR_DT:?}" \
              -v NY_YEAR_START_DT="${NY_YEAR_START_DT:?}" \
              -v NY_YEAR_END_DT="${NY_YEAR_END_DT:?}" \
              -v NY_PERIOD_START_DT="${NY_PERIOD_START_DT:?}" \
              -v NY_PERIOD_END_DT="${NY_PERIOD_END_DT:?}" \
              -v NY_WEEK_START_DT="${NY_WEEK_START_DT:?}" \
              -v NY_WEEK_END_DT="${NY_WEEK_END_DT:?}" \
              -v NY_DAY_OF_YEAR_NUM="${NY_DAY_OF_YEAR_NUM:?}" \
              -v NY_DAY_OF_PERIOD_NUM="${NY_DAY_OF_PERIOD_NUM:?}" \
              -v NY_DAY_OF_WEEK_NUM="${NY_DAY_OF_WEEK_NUM:?}" \
              -v NY_WEEK_OF_YEAR_NUM="${NY_WEEK_OF_YEAR_NUM:?}" \
              -v NY_WEEK_OF_PERIOD_NUM="${NY_WEEK_OF_PERIOD_NUM:?}" \
              -v NY_PERIOD_OF_YEAR_NUM="${NY_PERIOD_OF_YEAR_NUM:?}" \
              -v NY_YEAR_WEEK="${NY_YEAR_WEEK:?}" \
              -v NY_YEAR_PERIOD="${NY_YEAR_PERIOD:?}" \
              -v NY_YEAR_NUM="${NY_YEAR_NUM:?}" \
              ${STEP_DIR:?}/FND2106.300.VALIDATE.sql

#-------------------------------------------------------------------------------
# Step 310 : Validate that there is 1 business date
#-------------------------------------------------------------------------------

step 310 Bteq -s "${SERVER:?}" -u "${LOGON:?}" \
              -v MET_V="${MET_V}" \
              -v JOB="${JOB:?}" \
              -v STEP_NO=310 \
              -v INSTANCE="${INSTANCE:?}" \
              -v STREAMID="${STREAMID:?}" \
              -v LDTK_DATE="${LDTK_DATE:?}" \
              -v LDTK_PREV_DATE="${LDTK_PREV_DATE:?}" \
              -v LDTK_NEXT_DATE="${LDTK_NEXT_DATE:?}" \
              -v RUN_ID="${RUN_ID:?}" \
              -v RUNID="${RUN_ID:?}" \
              -v EFF_FROM_DT="${EFF_FROM_DT:?}" \
              -v CALENDAR_DT="${CALENDAR_DT:?}" \
              -v YEAR_START_DT="${YEAR_START_DT:?}" \
              -v YEAR_END_DT="${YEAR_END_DT:?}" \
              -v PERIOD_START_DT="${PERIOD_START_DT:?}" \
              -v PERIOD_END_DT="${PERIOD_END_DT:?}" \
              -v WEEK_START_DT="${WEEK_START_DT:?}" \
              -v WEEK_END_DT="${WEEK_END_DT:?}" \
              -v DAY_OF_YEAR_NUM="${DAY_OF_YEAR_NUM:?}" \
              -v DAY_OF_PERIOD_NUM="${DAY_OF_PERIOD_NUM:?}" \
              -v DAY_OF_WEEK_NUM="${DAY_OF_WEEK_NUM:?}" \
              -v WEEK_OF_YEAR_NUM="${WEEK_OF_YEAR_NUM:?}" \
              -v WEEK_OF_PERIOD_NUM="${WEEK_OF_PERIOD_NUM:?}" \
              -v PERIOD_OF_YEAR_NUM="${PERIOD_OF_YEAR_NUM:?}" \
              -v YEAR_WEEK="${YEAR_WEEK:?}" \
              -v YEAR_PERIOD="${YEAR_PERIOD:?}" \
              -v YEAR_NUM="${YEAR_NUM:?}" \
              -v SEASON_CODE="${SEASON_CODE:?}" \
              -v SEASON_NAME="${SEASON_NAME:?}" \
              -v SEASON_DESCRIPTION="${SEASON_DESCRIPTION:?}" \
              -v LY_CALENDAR_DT="${LY_CALENDAR_DT:?}" \
              -v LY_YEAR_START_DT="${LY_YEAR_START_DT:?}" \
              -v LY_YEAR_END_DT="${LY_YEAR_END_DT:?}" \
              -v LY_PERIOD_START_DT="${LY_PERIOD_START_DT:?}" \
              -v LY_PERIOD_END_DT="${LY_PERIOD_END_DT:?}" \
              -v LY_WEEK_START_DT="${LY_WEEK_START_DT:?}" \
              -v LY_WEEK_END_DT="${LY_WEEK_END_DT:?}" \
              -v LY_DAY_OF_YEAR_NUM="${LY_DAY_OF_YEAR_NUM:?}" \
              -v LY_DAY_OF_PERIOD_NUM="${LY_DAY_OF_PERIOD_NUM:?}" \
              -v LY_DAY_OF_WEEK_NUM="${LY_DAY_OF_WEEK_NUM:?}" \
              -v LY_WEEK_OF_YEAR_NUM="${LY_WEEK_OF_YEAR_NUM:?}" \
              -v LY_WEEK_OF_PERIOD_NUM="${LY_WEEK_OF_PERIOD_NUM:?}" \
              -v LY_PERIOD_OF_YEAR_NUM="${LY_PERIOD_OF_YEAR_NUM:?}" \
              -v LY_YEAR_WEEK="${LY_YEAR_WEEK:?}" \
              -v LY_YEAR_PERIOD="${LY_YEAR_PERIOD:?}" \
              -v LY_YEAR_NUM="${LY_YEAR_NUM:?}" \
              -v LLY_CALENDAR_DT="${LLY_CALENDAR_DT:?}" \
              -v LLY_YEAR_START_DT="${LLY_YEAR_START_DT:?}" \
              -v LLY_YEAR_END_DT="${LLY_YEAR_END_DT:?}" \
              -v LLY_PERIOD_START_DT="${LLY_PERIOD_START_DT:?}" \
              -v LLY_PERIOD_END_DT="${LLY_PERIOD_END_DT:?}" \
              -v LLY_WEEK_START_DT="${LLY_WEEK_START_DT:?}" \
              -v LLY_WEEK_END_DT="${LLY_WEEK_END_DT:?}" \
              -v LLY_DAY_OF_YEAR_NUM="${LLY_DAY_OF_YEAR_NUM:?}" \
              -v LLY_DAY_OF_PERIOD_NUM="${LLY_DAY_OF_PERIOD_NUM:?}" \
              -v LLY_DAY_OF_WEEK_NUM="${LLY_DAY_OF_WEEK_NUM:?}" \
              -v LLY_WEEK_OF_YEAR_NUM="${LLY_WEEK_OF_YEAR_NUM:?}" \
              -v LLY_WEEK_OF_PERIOD_NUM="${LLY_WEEK_OF_PERIOD_NUM:?}" \
              -v LLY_PERIOD_OF_YEAR_NUM="${LLY_PERIOD_OF_YEAR_NUM:?}" \
              -v LLY_YEAR_WEEK="${LLY_YEAR_WEEK:?}" \
              -v LLY_YEAR_PERIOD="${LLY_YEAR_PERIOD:?}" \
              -v LLY_YEAR_NUM="${LLY_YEAR_NUM:?}" \
              -v LLLY_CALENDAR_DT="${LLLY_CALENDAR_DT:?}" \
              -v LLLY_YEAR_START_DT="${LLLY_YEAR_START_DT:?}" \
              -v LLLY_YEAR_END_DT="${LLLY_YEAR_END_DT:?}" \
              -v LLLY_PERIOD_START_DT="${LLLY_PERIOD_START_DT:?}" \
              -v LLLY_PERIOD_END_DT="${LLLY_PERIOD_END_DT:?}" \
              -v LLLY_WEEK_START_DT="${LLLY_WEEK_START_DT:?}" \
              -v LLLY_WEEK_END_DT="${LLLY_WEEK_END_DT:?}" \
              -v LLLY_DAY_OF_YEAR_NUM="${LLLY_DAY_OF_YEAR_NUM:?}" \
              -v LLLY_DAY_OF_PERIOD_NUM="${LLLY_DAY_OF_PERIOD_NUM:?}" \
              -v LLLY_DAY_OF_WEEK_NUM="${LLLY_DAY_OF_WEEK_NUM:?}" \
              -v LLLY_WEEK_OF_YEAR_NUM="${LLLY_WEEK_OF_YEAR_NUM:?}" \
              -v LLLY_WEEK_OF_PERIOD_NUM="${LLLY_WEEK_OF_PERIOD_NUM:?}" \
              -v LLLY_PERIOD_OF_YEAR_NUM="${LLLY_PERIOD_OF_YEAR_NUM:?}" \
              -v LLLY_YEAR_WEEK="${LLLY_YEAR_WEEK:?}" \
              -v LLLY_YEAR_PERIOD="${LLLY_YEAR_PERIOD:?}" \
              -v LLLY_YEAR_NUM="${LLLY_YEAR_NUM:?}" \
              -v NY_CALENDAR_DT="${NY_CALENDAR_DT:?}" \
              -v NY_YEAR_START_DT="${NY_YEAR_START_DT:?}" \
              -v NY_YEAR_END_DT="${NY_YEAR_END_DT:?}" \
              -v NY_PERIOD_START_DT="${NY_PERIOD_START_DT:?}" \
              -v NY_PERIOD_END_DT="${NY_PERIOD_END_DT:?}" \
              -v NY_WEEK_START_DT="${NY_WEEK_START_DT:?}" \
              -v NY_WEEK_END_DT="${NY_WEEK_END_DT:?}" \
              -v NY_DAY_OF_YEAR_NUM="${NY_DAY_OF_YEAR_NUM:?}" \
              -v NY_DAY_OF_PERIOD_NUM="${NY_DAY_OF_PERIOD_NUM:?}" \
              -v NY_DAY_OF_WEEK_NUM="${NY_DAY_OF_WEEK_NUM:?}" \
              -v NY_WEEK_OF_YEAR_NUM="${NY_WEEK_OF_YEAR_NUM:?}" \
              -v NY_WEEK_OF_PERIOD_NUM="${NY_WEEK_OF_PERIOD_NUM:?}" \
              -v NY_PERIOD_OF_YEAR_NUM="${NY_PERIOD_OF_YEAR_NUM:?}" \
              -v NY_YEAR_WEEK="${NY_YEAR_WEEK:?}" \
              -v NY_YEAR_PERIOD="${NY_YEAR_PERIOD:?}" \
              -v NY_YEAR_NUM="${NY_YEAR_NUM:?}" \
              ${STEP_DIR:?}/FND2106.310.VALIDATE.sql


#------------------------------------------------------------------------------------
# Step 900 : Job Stop
#------------------------------------------------------------------------------------

step 900 Bteq -s "${SERVER:?}" -u "${LOGON:?}" -v MET_V="${MET_V}" \
              -v INSERTED_STAGING="${INSERTED_STAGING}" \
              -v REJECTED_STAGING="${REJECTED_STAGING}" \
              -v DUPLICATE_STAGING="${DUPLICATE_STAGING}" \
              -v INSERTED_TARGET="${INSERTED_TARGET}" \
              -v REJECTED_TARGET="${REJECTED_TARGET}" \
              -v DUPLICATE_TARGET="${DUPLICATE_TARGET}" \
              -v RUN_ID="${RUN_ID}" \
              -v STEP_NO="900" -v INSTANCE="${INSTANCE:?}" \
              -v JOB="${JOB:?}" ${STEP_DIR:?}/FND_JobStop.sql

#-----------------------------------------------------------
# End
#-----------------------------------------------------------